pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
        maven("https://repo.spring.io/milestone")
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev")
        maven("https://androidx.dev/storage/compose-compiler/repository/")
        maven("https://jitpack.io")
        maven("https://raw.githubusercontent.com/graalvm/native-build-tools/snapshots")
    }
}

dependencyResolutionManagement {
    // repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
        google()
        maven("https://repo.spring.io/milestone")
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev")
        maven("https://maven.pkg.jetbrains.space/public/p/ktor/eap")
        maven("https://androidx.dev/storage/compose-compiler/repository/")
        maven("https://jitpack.io")
        maven("https://repo.kotlin.link")
        maven("https://oss.sonatype.org/content/repositories/snapshots")
        maven("https://repo.gradle.org/gradle/libs-releases")
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = "kotlinw"

// include(":kotlinw-compose")
include(":kotlinw-configuration-core")
include(":kotlinw-configuration-toml")
include(":kotlinw-di-api")
include(":kotlinw-di-processor")
include(":kotlinw-di-test")
include(":kotlinw-eventbus-inprocess")
include(":kotlinw-graph")
include(":kotlinw-hibernate-api")
include(":kotlinw-hibernate-core")
include(":kotlinw-hibernate-processor")
include(":kotlinw-i18n-core-mp")
include(":kotlinw-immutator-annotations")
include(":kotlinw-immutator-api")
include(":kotlinw-immutator-example-webapp")
include(":kotlinw-immutator-processor")
include(":kotlinw-immutator-test")
include(":kotlinw-integration-bulma-compose")
include(":kotlinw-io")
include(":kotlinw-jdbc-util")
include(":kotlinw-js-oauth")
include(":kotlinw-jwt-core")
include(":kotlinw-keycloak-client-core")
include(":kotlinw-keyvaluestore-api")
include(":kotlinw-keyvaluestore-core")
include(":kotlinw-keyvaluestore-platform")
include(":kotlinw-ksp-processor")
include(":kotlinw-ksp-testutil")
include(":kotlinw-ksp-util")
include(":kotlinw-logging-api")
include(":kotlinw-logging-js-console")
include(":kotlinw-logging-jvm-logback")
include(":kotlinw-logging-jvm-slf4j")
include(":kotlinw-logging-platform")
include(":kotlinw-logging-spi")
include(":kotlinw-logging-stdout")
include(":kotlinw-markdown-compose")
include(":kotlinw-markdown-core")
include(":kotlinw-oauth2-core")
include(":kotlinw-oauth2-ktor-client")
include(":kotlinw-oauth2-ktor-server")
include(":kotlinw-objectstore-api")
include(":kotlinw-objectstore-core")
include(":kotlinw-objectstore-platform")
include(":kotlinw-pwa-core")
include(":kotlinw-remoting-api")
include(":kotlinw-remoting-compose")
include(":kotlinw-remoting-core")
include(":kotlinw-remoting-core-ktor")
include(":kotlinw-remoting-client-ktor")
include(":kotlinw-remoting-ipc")
include(":kotlinw-remoting-processor")
include(":kotlinw-remoting-processor-test")
include(":kotlinw-remoting-server-ktor")
include(":kotlinw-serialization-core")
// include(":kotlinw-statemachine-compose")
include(":kotlinw-statemachine-core")
// include(":kotlinw-statemachine-example-desktop")
// include(":kotlinw-statemachine-example-webapp")
include(":kotlinw-ulid")
include(":kotlinw-util-core-mp")
include(":kotlinw-util-coroutine-mp")
include(":kotlinw-util-datetime-mp")
include(":kotlinw-util-ktor-client")
include(":kotlinw-util-serialization-json")
include(":kotlinw-util-stdlib-mp")
include(":kotlinw-util-unit")
include(":kotlinw-uuid")

include(":module:kotlinw-module-api")
include(":module:kotlinw-module-appbase")
include(":module:kotlinw-module-auth-core")
include(":module:kotlinw-module-core")
include(":module:kotlinw-module-hibernate")
include(":module:kotlinw-module-hibernate-configuration")
include(":module:kotlinw-module-ktor-server")
include(":module:kotlinw-module-remoting-client")
include(":module:kotlinw-module-remoting-server")
include(":module:kotlinw-module-remoting-shared")
include(":module:kotlinw-module-serverbase")
include(":module:kotlinw-module-serverbase-internal-test")
include(":module:kotlinw-module-test")
include(":module:kotlinw-module-webapp-client")
include(":module:kotlinw-module-webapp-server")
