[versions]

# https://github.com/JetBrains/kotlin
kotlin = "1.7.10"

# https://junit.org/junit5/docs/current/release-notes/index.html
junit = "5.9.0"

# https://github.com/Kotlin/kotlinx.serialization/releases
serialization = "1.4.0"

# https://github.com/Kotlin/kotlinx.coroutines/releases
coroutines = "1.6.4"

# https://github.com/DevSrSouza/compose-icons/releases
devsrsouzaComposeIcons = "1.0.0"

# https://github.com/JetBrains/compose-jb/releases
composeVersion = "1.2.0-alpha01-dev770"

[libraries]

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

jetbrains-compose-web-core = { module = "org.jetbrains.compose.web:web-core", version.ref = "composeVersion" }
jetbrains-compose-web-core-js = { module = "org.jetbrains.compose.web:web-core-js", version.ref = "composeVersion" }
jetbrains-compose-material-materialiconsextended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeVersion" }

# https://github.com/DevSrSouza/compose-icons/blob/master/simple-icons/DOCUMENTATION.md
devsrsouza-compose-icons-simpleicons = { module = "br.com.devsrsouza.compose.icons.jetbrains:simple-icons", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/feather/DOCUMENTATION.md
devsrsouza-compose-icons-feather = { module = "br.com.devsrsouza.compose.icons.jetbrains:feather", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/tabler-icons/DOCUMENTATION.md
devsrsouza-compose-icons-tablericons = { module = "br.com.devsrsouza.compose.icons.jetbrains:tabler-icons", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/eva-icons/DOCUMENTATION.md
devsrsouza-compose-icons-evaicons = { module = "br.com.devsrsouza.compose.icons.jetbrains:eva-icons", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/font-awesome/DOCUMENTATION.md
devsrsouza-compose-icons-fontawesome = { module = "br.com.devsrsouza.compose.icons.jetbrains:font-awesome", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/octicons/DOCUMENTATION.md
devsrsouza-compose-icons-octicons = { module = "br.com.devsrsouza.compose.icons.jetbrains:octicons", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/linea/DOCUMENTATION.md
devsrsouza-compose-icons-linea = { module = "br.com.devsrsouza.compose.icons.jetbrains:linea", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/line-awesome/DOCUMENTATION.md
devsrsouza-compose-icons-lineawesome = { module = "br.com.devsrsouza.compose.icons.jetbrains:line-awesome", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/erikflowers-weather-icons/DOCUMENTATION.md
devsrsouza-compose-icons-erikflowersweathericons = { module = "br.com.devsrsouza.compose.icons.jetbrains:erikflowers-weather-icons", version.ref = "devsrsouzaComposeIcons" }
# https://github.com/DevSrSouza/compose-icons/blob/master/css-gg/DOCUMENTATION.md
devsrsouza-compose-icons-cssgg = { module = "br.com.devsrsouza.compose.icons.jetbrains:css-gg", version.ref = "devsrsouzaComposeIcons" }

# https://github.com/Kotlin/kotlinx.collections.immutable/releases
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }

# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# https://github.com/MicroUtils/kotlin-logging/releases
kotlin-logging = { module = "io.github.microutils:kotlin-logging", version = "2.1.23" }

[plugins]
