[versions]

# https://github.com/JetBrains/kotlin
kotlin = "1.6.10"

# https://junit.org/junit5/docs/current/release-notes/index.html
junit = "5.8.2"

# https://github.com/Kotlin/kotlinx.serialization/releases
serialization = "1.3.2"

[libraries]

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

# https://github.com/Kotlin/kotlinx.collections.immutable/releases
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }

# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.3.2" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

[plugins]
